name: ml_workshop
channels:
  - defaults
dependencies:
  - argon2-cffi=20.1.0
  - async_generator=1.10
  - attrs=20.3.0
  - backcall=0.2.0
  - blas=1.0
  - bleach=3.2.1
  - blosc=1.20.1
  - brotli=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2021.1.19
  - certifi=2020.12.5
  - cffi=1.14.4
  - charls=2.1.0
  - cloudpickle=1.6.0
  - colorama=0.4.4
  - cycler=0.10.0
  - cytoolz=0.11.0
  - dask-core=2021.1.0
  - decorator=4.4.2
  - defusedxml=0.6.0
  - entrypoints=0.3
  - freetype=2.10.4
  - giflib=5.2.1
  - icc_rt=2019.0.0
  - icu=58.2
  - imagecodecs=2021.1.11
  - imageio=2.9.0
  - importlib-metadata=2.0.0
  - importlib_metadata=2.0.0
  - intel-openmp=2020.2
  - ipykernel=5.3.4
  - ipython=7.19.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.3
  - jedi=0.18.0
  - jinja2=2.11.2
  - joblib=1.0.0
  - jpeg=9b
  - jsonschema=3.2.0
  - jupyter=1.0.0
  - jupyter_client=6.1.7
  - jupyter_console=6.2.0
  - jupyter_core=4.7.0
  - jupyterlab_pygments=0.1.2
  - jupyterlab_widgets=1.0.0
  - kiwisolver=1.3.0
  - lcms2=2.11
  - lerc=2.2.1
  - libaec=1.0.4
  - libdeflate=1.7
  - libpng=1.6.37
  - libsodium=1.0.18
  - libtiff=4.1.0
  - libzopfli=1.0.3
  - lz4-c=1.9.3
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - markupsafe=1.1.1
  - matplotlib=3.3.2
  - matplotlib-base=3.3.2
  - mistune=0.8.4
  - mkl=2020.2
  - mkl-service=2.3.0
  - mkl_fft=1.0.6
  - mkl_random=1.0.2
  - msys2-conda-epoch=20160418
  - nbclient=0.5.1
  - nbconvert=6.0.7
  - nbformat=5.1.2
  - nest-asyncio=1.4.3
  - networkx=2.5
  - notebook=6.1.6
  - numpy=1.19.2
  - numpy-base=1.19.2
  - olefile=0.46
  - openjpeg=2.3.0
  - openssl=1.1.1i
  - packaging=20.8
  - pandas=1.2.1
  - pandoc=2.11
  - pandocfilters=1.4.3
  - parso=0.7.0
  - pickleshare=0.7.5
  - pillow=8.1.0
  - pip=20.3.3
  - prometheus_client=0.9.0
  - prompt-toolkit=3.0.8
  - prompt_toolkit=3.0.8
  - pycparser=2.20
  - pygments=2.7.4
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - pyrsistent=0.17.3
  - python=3.9.1
  - python-dateutil=2.8.1
  - pytz=2020.5
  - pywavelets=1.1.1
  - pywin32=228
  - pywinpty=0.5.7
  - pyyaml=5.4
  - pyzmq=20.0.0
  - qt=5.9.7
  - qtconsole=4.7.7
  - qtpy=1.9.0
  - scikit-image=0.17.2
  - scikit-learn=0.23.2
  - scipy=1.5.2
  - send2trash=1.5.0
  - setuptools=51.3.3
  - sip=4.19.13
  - six=1.15.0
  - snappy=1.1.8
  - sqlite=3.33.0
  - terminado=0.9.2
  - testpath=0.4.4
  - threadpoolctl=2.1.0
  - tifffile=2021.1.14
  - tk=8.6.10
  - toolz=0.11.1
  - tornado=6.1
  - traitlets=5.0.5
  - tzdata=2020d
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.36.2
  - widgetsnbextension=3.5.1
  - wincertstore=0.2
  - winpty=0.4.3
  - xz=5.2.5
  - yaml=0.2.5
  - zeromq=4.3.3
  - zfp=0.5.5
  - zipp=3.4.0
  - zlib=1.2.11
  - zstd=1.4.5
